In [1]:
import os
import pandas as pd
import numpy as np

In [2]:
os.chdir("C:/Users/amri.kyaruzi/Python Projects/Work")

In [3]:
data = pd.read_csv("Jan - December 2021 Closed Charts.csv")

In [4]:
data.head(5)

,Unnamed: 0,AKNO,Month,Quarter,DOCTOR,DEPT,SNN,DOCUMENTS,TYPE,DOCUMENTED,TIMELY,LEGIBLE,COMPLETE,MET
0,1,054-99-30,Jan,Q1,Nahida Walli,Paediatrics,1.1,Physician Initial Assessment,P,Y,Y,N,Y,N
1,2,054-99-30,Jan,Q1,Nahida Walli,Paediatrics,1.2,Nursing Initial Assessment,N,Y,Y,Y,Y,Y
2,3,054-99-30,Jan,Q1,Nahida Walli,Paediatrics,1.4,Pain Assessment & Reassessment,N,Y,Y,Y,N,N
3,4,054-99-30,Jan,Q1,Nahida Walli,Paediatrics,1.8,Nursing Care Plan,N,N,-,-,-,N
4,5,054-99-30,Jan,Q1,Nahida Walli,Paediatrics,2.1,Round Notes (SBAR),P,Y,Y,N,Y,N

In [5]:
data1 = data[["AKNO", "Month", "DOCTOR", "DEPT", "DOCUMENTS", "MET"]]

In [6]:
data1["DOCUMENTS"].unique()

array(['Physician Initial Assessment', 'Nursing Initial Assessment',
       'Pain Assessment & Reassessment', 'Nursing Care Plan',
       'Round Notes (SBAR)', 'MEWS, NEWS, PEWS & MEOWS',
       'Fall Risk Assessment',
       'Multidisciplinary Patient and Family Education',
       'Physician Orders', 'Physician Orders - Countersigning',
       "CPOE orders - Nurse's Signature", 'STAT medications',
       'Informed Consent', 'Discharge summaries without Abbreviations',
       'Consent forms without Abbreviations',
       'Blood Transfusion Monitoring', 'Blood Transfusion Order',
       'Discharge summary', 'Site Marking, Sign in, Time out & Sign out',
       'Procedure/ Operative notes', "CPOE orders - Doctor's Signature",
       'Pre-Anaesthesia/Sedation Assessment', 'Physiotherapy Assessment',
       'Physiotherapy Fall Risk Assessment', 'Nutritional Assessment',
       'Pre-Induction Assessment', 'Post-Anaesthesia Recovery',
       'Intraoperative Notes of Anesthesia',
       'PRN Analgesic Orders - Appropriateness of Administration',
       'Procedure Notes - Surgical Specimen Documentation',
       "Multidisciplinary Patient and Family Education Form (Doctor's Part)",
       "Multidisciplinary Patient and Family Education Form (Nurse's Part)"],
      dtype=object)

In [7]:
#Nursing care plan
#BT (not a parameter, what files have? are complete?)
#STAT medications
#CPOE orders - doctors signature

In [8]:
data2 = data1[(data1["DOCUMENTS"] == "Informed Consent") | (data1["DOCUMENTS"] == "Physician Initial Assessment") |
              (data1["DOCUMENTS"] == "Nursing Initial Assessment") | (data1["DOCUMENTS"] == "CPOE orders - Nurse's Signature") |
              (data1["DOCUMENTS"] == "CPOE orders - Doctor's Signature") |
              (data1["DOCUMENTS"] == "Multidisciplinary Patient and Family Education") | (data1["DOCUMENTS"] == "Procedure/ Operative notes") |
              (data1["DOCUMENTS"] == "Site Marking, Sign in, Time out & Sign out") | (data1["DOCUMENTS"] == "STAT medications") | 
              (data1["DOCUMENTS"] == "Multidisciplinary Patient and Family Education Form (Doctor's Part)") | 
              (data1["DOCUMENTS"] == "Multidisciplinary Patient and Family Education Form (Nurse's Part)")]

In [9]:
data2["DEPT"].unique()

array(['Paediatrics', 'Surgery', 'Maternity', 'Medicine', 'Physiotherapy',
       'Nutrition', 'Anaesthesia', 'A&E'], dtype=object)

In [10]:
data2 = data2[(data2["MET"] == "Y")|(data2["MET"] == "N")]
data2 = data2[(data2["DEPT"] == "Surgery")|
              (data2["DEPT"] == "Maternity")|
              (data2["DEPT"] == "Medicine")|
              (data2["DEPT"] == "Paediatrics")]

In [11]:
index_list = ["AKNO", "DEPT", "DOCTOR", "Month"]
data3 = data2.pivot_table(index = index_list, columns = "DOCUMENTS", values = "MET", aggfunc= np.sum)

In [12]:
data3.reset_index()

DOCUMENTS,AKNO,DEPT,DOCTOR,Month,CPOE orders - Doctor's Signature,CPOE orders - Nurse's Signature,Informed Consent,Multidisciplinary Patient and Family Education,Multidisciplinary Patient and Family Education Form (Doctor's Part),Multidisciplinary Patient and Family Education Form (Nurse's Part),Nursing Initial Assessment,Physician Initial Assessment,Procedure/ Operative notes,STAT medications,"Site Marking, Sign in, Time out & Sign out"
0,000-00-38,Medicine,Mandela Makakala,Dec,NaN,Y,NaN,NaN,Y,Y,Y,N,NaN,Y,NaN
1,000-01-47,Surgery,Felix Mrita,Mar,NaN,Y,Y,N,NaN,NaN,N,N,N,N,N
2,000-02-39,Surgery,Aidan Njau,Feb,NaN,Y,N,N,NaN,NaN,N,Y,N,Y,Y
3,000-08-27,Surgery,Aidan Njau,Jun,NaN,Y,Y,N,NaN,NaN,N,N,N,Y,Y
4,000-20-16,Medicine,Fatma Bakshi,Aug,NaN,Y,NaN,Y,NaN,NaN,Y,N,NaN,Y,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1679,270-12-20,Maternity,Jane Muzo,Mar,NaN,Y,N,N,NaN,NaN,N,N,Y,N,N
1680,270-13-16,Surgery,Athar Ali,Nov,NaN,Y,N,NaN,Y,Y,Y,N,Y,Y,Y
1681,270-17-01,Surgery,Rajeev Kumar,Jun,NaN,Y,Y,Y,NaN,NaN,Y,N,Y,Y,N
1682,270-17-12,Paediatrics,Nahida Walli,Oct,NaN,Y,NaN,NaN,Y,Y,Y,N,NaN,Y,NaN
1683,295-47-99,Surgery,Aidan Njau,Dec,NaN,Y,Y,NaN,N,Y,Y,Y,Y,N,Y

In [13]:
data3.fillna("N/A", inplace = True)

In [14]:
data3['Use for JCIA'] = np.where((
                                  ((data3['Informed Consent']=='N/A') | (data3['Informed Consent'] == 'Y')) &
                                  ((data3["CPOE orders - Nurse's Signature"] == "Y") | (data3["CPOE orders - Nurse's Signature"] == "N/A"))&
                                  ((data3["STAT medications"] == "Y") | (data3["STAT medications"] == "N/A")) &
                                  ((data3["Site Marking, Sign in, Time out & Sign out"] == "Y") | (data3["Site Marking, Sign in, Time out & Sign out"] == "N/A")) &
                                  ((data3["Procedure/ Operative notes"] == "Y") | (data3["Procedure/ Operative notes"] == "N/A")) &
                                  ((data3["Multidisciplinary Patient and Family Education Form (Doctor's Part)"] == "Y") |
                                   (data3["Multidisciplinary Patient and Family Education Form (Doctor's Part)"] == "N/A")) &
                                  ((data3["Multidisciplinary Patient and Family Education Form (Nurse's Part)"] == "Y") |
                                   (data3["Multidisciplinary Patient and Family Education Form (Nurse's Part)"] == "N/A")) & 
                                  ((data3["Multidisciplinary Patient and Family Education"] == "Y") |
                                   (data3["Multidisciplinary Patient and Family Education"] == "N/A")) &
                                  ((data3["CPOE orders - Doctor's Signature"] == "Y") | (data3["CPOE orders - Doctor's Signature"] == "N/A"))
                                  ), 'Maybe', 'No')

In [15]:
#data3['Use for JCIA'] = np.where((((data3['Informed Consent']=='N/A') | (data3['Informed Consent'] == 'Y'))), 'Yes', 'No')

In [16]:
data3 = data3.reset_index()
data3 = data3[data3["Month"].isin(["Jul", "Aug", "Sep", "Oct", "Nov", "Dec"])]
data3.shape

(900, 16)

In [17]:
new_order = ["Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
data3["Month"] = pd.Categorical(data3["Month"], categories=new_order, ordered=True)
data3 = data3.sort_values(by="Month", ascending=True).reset_index()

#pd.to_datetime(data3["Month"], format="%b", errors="coerce").dt.month

In [18]:
data3.head(10)

DOCUMENTS,index,AKNO,DEPT,DOCTOR,Month,CPOE orders - Doctor's Signature,CPOE orders - Nurse's Signature,Informed Consent,Multidisciplinary Patient and Family Education,Multidisciplinary Patient and Family Education Form (Doctor's Part),Multidisciplinary Patient and Family Education Form (Nurse's Part),Nursing Initial Assessment,Physician Initial Assessment,Procedure/ Operative notes,STAT medications,"Site Marking, Sign in, Time out & Sign out",Use for JCIA
0,744,140-49-14,Surgery,Aidan Njau,Jul,N/A,Y,Y,Y,N/A,N/A,Y,Y,Y,N,N,No
1,282,041-31-07,Paediatrics,Maria Bulimba,Jul,N/A,N/A,N/A,N,N/A,N/A,Y,N,N/A,N/A,N/A,No
2,288,041-73-22,Medicine,Mandela Makakala,Jul,N/A,Y,N/A,N,N/A,N/A,Y,N,N/A,Y,N/A,No
3,962,158-19-26,Medicine,Phillip Adebayo,Jul,N/A,N/A,N/A,N,N/A,N/A,Y,Y,N/A,N/A,N/A,No
4,294,042-29-20,Maternity,Munawwar Kaguta,Jul,N/A,Y,Y,Y,N/A,N/A,N,N,N,N,N,No
5,296,042-89-03,Maternity,Jane Muzo,Jul,N/A,Y,Y,Y,N/A,N/A,N,N,N,Y,Y,No
6,942,157-83-11,Surgery,Aidan Njau,Jul,N/A,N/A,N,N,N/A,N/A,N,N,Y,N/A,N,No
7,938,157-76-83,Medicine,Aleesha Adatia,Jul,N/A,N/A,N/A,N,N/A,N/A,Y,N,N/A,N/A,N/A,No
8,929,157-56-04,Medicine,Kamran Hameed,Jul,N/A,Y,N/A,N,N/A,N/A,N,N,N/A,N,N/A,No
9,928,157-55-34,Maternity,Shweta Jaiswal,Jul,N/A,Y,N/A,N,N/A,N/A,N,Y,N/A,Y,N/A,No

In [19]:
#(data3.groupby(["Month", "DEPT"])["Use for JCIA"].value_counts()).rename("Totals").reset_index()
data3.groupby(["Month", "DEPT"])["Use for JCIA"].value_counts().reset_index(name = "Totals")

   Month         DEPT Use for JCIA  Totals
0    Jul    Maternity           No      35
1    Jul    Maternity        Maybe       4
2    Jul     Medicine           No      35
3    Jul     Medicine        Maybe       8
4    Jul  Paediatrics           No      17
5    Jul  Paediatrics        Maybe      12
6    Jul      Surgery           No      39
7    Jul      Surgery        Maybe       6
8    Aug    Maternity           No      33
9    Aug    Maternity        Maybe       5
10   Aug     Medicine           No      31
11   Aug     Medicine        Maybe      12
12   Aug  Paediatrics           No      21
13   Aug  Paediatrics        Maybe       7
14   Aug      Surgery           No      35
15   Aug      Surgery        Maybe       7
16   Sep    Maternity           No      23
17   Sep    Maternity        Maybe       5
18   Sep     Medicine           No      19
19   Sep     Medicine        Maybe       9
20   Sep  Paediatrics           No      17
21   Sep  Paediatrics        Maybe       8
22   Sep      Surgery           No      41
23   Sep      Surgery        Maybe      11
24   Oct    Maternity           No      28
25   Oct    Maternity        Maybe       5
26   Oct     Medicine           No      21
27   Oct     Medicine        Maybe      16
28   Oct  Paediatrics           No      21
29   Oct  Paediatrics        Maybe       8
30   Oct      Surgery           No      40
31   Oct      Surgery        Maybe      15
32   Nov    Maternity           No      34
33   Nov    Maternity        Maybe       7
34   Nov     Medicine           No      32
35   Nov     Medicine        Maybe       6
36   Nov  Paediatrics           No      29
37   Nov  Paediatrics        Maybe       3
38   Nov      Surgery           No      40
39   Nov      Surgery        Maybe       2
40   Dec    Maternity           No      27
41   Dec    Maternity        Maybe       6
42   Dec     Medicine           No      24
43   Dec     Medicine        Maybe      10
44   Dec  Paediatrics           No      21
45   Dec  Paediatrics        Maybe       4
46   Dec      Surgery           No      59
47   Dec      Surgery        Maybe       2

Oncology

In [20]:
#data3 = data3[((data3["DOCTOR"] == "Aleesha Adatia") | (data3["DOCTOR"] == "Harrison Chuwa"))]
#(data3.groupby(["Month", "DOCTOR"])["Use for JCIA"].value_counts()).rename("Totals").reset_index()

In [21]:
#Institutional total per month
(data3.groupby(["Month"])["Use for JCIA"].value_counts()).rename("Totals").reset_index()

   Month Use for JCIA  Totals
0    Jul           No     126
1    Jul        Maybe      30
2    Aug           No     120
3    Aug        Maybe      31
4    Sep           No     100
5    Sep        Maybe      33
6    Oct           No     110
7    Oct        Maybe      44
8    Nov           No     135
9    Nov        Maybe      18
10   Dec           No     131
11   Dec        Maybe      22

In [22]:
#Institutional total - overall
data3["Use for JCIA"].value_counts()

No       722
Maybe    178
Name: Use for JCIA, dtype: int64

Surgery

In [23]:
surgery = data3[data3["DEPT"] == "Surgery"]
surgery.head(5)

DOCUMENTS,index,AKNO,DEPT,DOCTOR,Month,CPOE orders - Doctor's Signature,CPOE orders - Nurse's Signature,Informed Consent,Multidisciplinary Patient and Family Education,Multidisciplinary Patient and Family Education Form (Doctor's Part),Multidisciplinary Patient and Family Education Form (Nurse's Part),Nursing Initial Assessment,Physician Initial Assessment,Procedure/ Operative notes,STAT medications,"Site Marking, Sign in, Time out & Sign out",Use for JCIA
0,744,140-49-14,Surgery,Aidan Njau,Jul,N/A,Y,Y,Y,N/A,N/A,Y,Y,Y,N,N,No
6,942,157-83-11,Surgery,Aidan Njau,Jul,N/A,N/A,N,N,N/A,N/A,N,N,Y,N/A,N,No
19,338,046-57-30,Surgery,Athar Ali,Jul,N/A,N/A,Y,Y,N/A,N/A,N,Y,Y,Y,Y,Maybe
22,996,158-82-26,Surgery,Christopher Mwansasu,Jul,N/A,N/A,Y,Y,N/A,N/A,Y,N,N,N,N,No
23,1006,159-10-42,Surgery,Hussam Soomro,Jul,N/A,Y,N/A,Y,N/A,N/A,Y,Y,N/A,Y,N/A,Maybe

In [24]:
surgery.groupby("Month")["Use for JCIA"].value_counts().reset_index(name = "Totals")

   Month Use for JCIA  Totals
0    Jul           No      39
1    Jul        Maybe       6
2    Aug           No      35
3    Aug        Maybe       7
4    Sep           No      41
5    Sep        Maybe      11
6    Oct           No      40
7    Oct        Maybe      15
8    Nov           No      40
9    Nov        Maybe       2
10   Dec           No      59
11   Dec        Maybe       2

In [25]:
surgery = surgery[surgery["Use for JCIA"] == "Maybe"]
surgery.to_excel("Surgery - Possible Files for Use.xlsx")